In [31]:
import pandas as pd
import numpy as np
import matplotlib as mp
import seaborn as sns
%matplotlib inline

pd.set_option('display.max_columns', 100)
mp.rcParams['figure.figsize'] = (20,15)

Описание POS тэгов (частей речи)

Number | Tag | Description
:--- | :--- | :---
1.	| CC | Coordinating conjunction
2.	| CD | Cardinal number
3.	| DT | Determiner
4.	| EX | Existential there
5.	|FW	|Foreign word
6.	|IN	|Preposition or subordinating conjunction
7.	|JJ	|Adjective
8.	|JJR |	Adjective, comparative
9.	|JJS|	Adjective, superlative
10.	|LS	|List item marker
11.	|MD	|Modal
12.	|NN	|Noun, singular or mass
13.	|NNS|	Noun, plural
14.	|NNP|	Proper noun, singular
15.	|NNPS|	Proper noun, plural
16.	|PDT|	Predeterminer
17.	|POS|	Possessive ending
18.	|PRP|	Personal pronoun
19.	|PRP\$|	Possessive pronoun
20.	|RB	|Adverb
21.	|RBR|	Adverb, comparative
22.	|RBS|	Adverb, superlative
23.	|RP	|Particle
24.	|SYM|	Symbol
25.	|TO	|to
26.	|UH	|Interjection
27.	|VB	|Verb, base form
28.	|VBD|	Verb, past tense
29.	|VBG|	Verb, gerund or present participle
30.	|VBN|	Verb, past participle
31.	|VBP|	Verb, non-3rd person singular present
32.	|VBZ|	Verb, 3rd person singular present
33.	|WDT|	Wh-determiner
34.	|WP	|Wh-pronoun
35.	|WP\$|	Possessive wh-pronoun
36.	|WRB|	Wh-adverb

Описание параметров

Колонка | Значение
:---: | :---
POS | форма слова, участвующая в тесте
word | слово
expected | лемма слова
real | результат лемматизации
word_operator | тестируемое средство
result | совпадает ли результат с ожидаемым

In [32]:
x = pd.read_csv('test_all.csv')

/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [33]:
x.head()

  type         word     expected         real        word_operator  result
0   NN  1-dodecanol  1-dodecanol  1-dodecanol  PHPMorphy_inflector       1
1   NN     1-hitter     1-hitter     1-hitter  PHPMorphy_inflector       1
2   NN      11-plus      11-plus      11-plus  PHPMorphy_inflector       1
3   NN     2-hitter     2-hitter     2-hitter  PHPMorphy_inflector       1
4   NN     3-hitter     3-hitter     3-hitter  PHPMorphy_inflector       1

In [34]:
x['word_operator'].unique()

array(['PHPMorphy_inflector', 'SimpleNLG_inflector', 'combined_tool',
       'en_inflectors_inflector'], dtype=object)

In [35]:
x.groupby('type').count()/3

               word       expected          real  word_operator         result
type
JJ     73924.000000   73924.000000  36896.000000   73925.333333   73925.333333
JJR     2997.333333    2997.333333   1496.333333    2997.333333    2997.333333
JJS     2541.333333    2541.333333   1268.333333    2541.333333    2541.333333
NN    105166.666667  105166.666667  51782.333333  105169.333333  105169.333333
NNS    96746.666667   96749.333333  47969.333333   96749.333333   96749.333333
VBD    11462.666667   11462.666667   5728.000000   11462.666667   11462.666667
VBG    11318.666667   11318.666667   5656.000000   11318.666667   11318.666667
VBN    11509.333333   11509.333333   5751.333333   11509.333333   11509.333333
VBP    11438.666667   11438.666667   5714.333333   11438.666667   11438.666667
VBZ    11189.333333   11189.333333   5590.333333   11189.333333   11189.333333

Посчитаем средние показатели для каждого средства

In [36]:
x.groupby('word_operator')['result'].mean()

word_operator
PHPMorphy_inflector        0.901441
SimpleNLG_inflector        0.000000
combined_tool              0.000000
en_inflectors_inflector    0.561708
Name: result, dtype: float64

Сделаем удобную таблицу результатов для анализа пар слов, с которыми не справляются средства

In [37]:
exact_word = pd.crosstab([x['type'],x['expected'],x['word']],[x['result'],x['word_operator']])[1]
exact_word

word_operator         PHPMorphy_inflector  en_inflectors_inflector
type expected word
JJ   1000th   1000th                    1                        1
     100th    100th                     1                        1
     10th     10th                      1                        1
     11th     11th                      1                        1
     12th     12th                      1                        1
     13th     13th                      1                        1
     14th     14th                      1                        1
     15th     15th                      1                        1
     16th     16th                      1                        1
     17th     17th                      1                        1
     18th     18th                      1                        1
     19th     19th                      1                        1
     1st      1st                       1                        1
     20th     20th                      1                        1
     21th     21th                      1                        1
     22th     22th                      1                        1
     23rd     23rd                      1                        1
     24th     24th                      1                        1
     25th     25th                      1                        1
     26th     26th                      1                        1
     27th     27th                      1                        1
     28th     28th                      1                        1
     29th     29th                      1                        1
     2d       2d                        0                        1
     2nd      2nd                       1                        1
     3-d      3-D                       0                        1
     30th     30th                      1                        1
     3rd      3rd                       1                        1
     4-h      4-H                       0                        1
     40th     40th                      1                        1
...                                   ...                      ...
VBZ  yaps     yap                       1                        0
     yarns    yarn                      1                        0
     yawns    yawn                      1                        0
     yawps    yawp                      1                        0
     yaws     yaw                       1                        0
     yeans    yean                      1                        0
     yearns   yearn                     1                        0
     yellows  yellow                    1                        0
     yells    yell                      1                        0
     yelps    yelp                      1                        0
     yeses    yes                       0                        0
     yesses   yes                       0                        0
     yields   yield                     1                        0
     yips     yip                       0                        0
     yodels   yodel                     1                        0
     yokes    yoke                      1                        0
     yowls    yowl                      1                        0
     yucks    yuck                      1                        0
     yuks     yuk                       1                        0
     zaps     zap                       1                        0
     zeroes   zero                      1                        0
     zeros    zero                      0                        0
     zigzags  zigzag                    1                        0
     zincks   zinc                      0                        0
     zincs    zinc                      1                        0
     zings    zing                      1                        0
     zippers  zipper                    0                        0
     zips     zip                       1                        0
     zones    zone                      1                        0
     zooms    zoom                      1                        0

[253720 rows x 2 columns]

Для взятия нужных строк/столбцов в такой структуре необходимо изпользовать мультииндекс

In [38]:
idx = pd.IndexSlice
exact_word.loc[idx[['VBD','VBN'],:,:],idx['NLTK_lemmatizer','PHPMorphy_inflector']]

/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py:972: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_nested_tuple(tup)

word_operator                NLTK_lemmatizer  PHPMorphy_inflector
type expected    word
VBD  abandoned   abandon                 NaN                    1
     abased      abase                   NaN                    1
     abashed     abash                   NaN                    1
     abated      abate                   NaN                    1
     abbreviated abbreviate              NaN                    1
     abdicated   abdicate                NaN                    1
     abduced     abduce                  NaN                    1
     abducted    abduct                  NaN                    1
     aberrated   aberrate                NaN                    1
     abetted     abet                    NaN                    1
     abhorred    abhor                   NaN                    1
     abided      abide                   NaN                    1
     abirritated abirritate              NaN                    1
     abjured     abjure                  NaN                    1
     ablated     ablate                  NaN                    1
     abnegated   abnegate                NaN                    1
     abode       abide                   NaN                    0
     abolished   abolish                 NaN                    1
     abominated  abominate               NaN                    1
     aborted     abort                   NaN                    1
     abounded    abound                  NaN                    1
     abraded     abrade                  NaN                    1
     abreacted   abreact                 NaN                    1
     abridged    abridge                 NaN                    1
     abrogated   abrogate                NaN                    1
     abscessed   abscess                 NaN                    0
     abscised    abscise                 NaN                    1
     absconded   abscond                 NaN                    1
     abseiled    abseil                  NaN                    1
     absented    absent                  NaN                    1
...                                      ...                  ...
VBN  yapped      yap                     NaN                    1
     yarned      yarn                    NaN                    1
     yawed       yaw                     NaN                    1
     yawned      yawn                    NaN                    1
     yawped      yawp                    NaN                    1
     yeaned      yean                    NaN                    1
     yearned     yearn                   NaN                    1
     yelled      yell                    NaN                    1
     yellowed    yellow                  NaN                    1
     yelped      yelp                    NaN                    1
     yesed       yes                     NaN                    0
     yessed      yes                     NaN                    0
     yielded     yield                   NaN                    1
     yipped      yip                     NaN                    0
     yodeled     yodel                   NaN                    1
     yodelled    yodel                   NaN                    0
     yoked       yoke                    NaN                    1
     yowled      yowl                    NaN                    1
     yucked      yuck                    NaN                    1
     yukked      yuk                     NaN                    0
     zapped      zap                     NaN                    1
     zeroed      zero                    NaN                    1
     zigzagged   zigzag                  NaN                    1
     zinced      zinc                    NaN                    1
     zincked     zinc                    NaN                    0
     zinged      zing                    NaN                    1
     zipped      zip                     NaN                    1
     zippered    zipper                  NaN                    0
     zoned       zone                    NaN                    1
     zoomed      zoom                    NaN                    1

[17229 rows x 2 columns]

Распрямим таблицу для выборки по столбцам

In [39]:
plane_exact_word = exact_word.reset_index()
plane_exact_word

word_operator,type,expected,word,PHPMorphy_inflector,en_inflectors_inflector
0,JJ,1000th,1000th,1,1
1,JJ,100th,100th,1,1
2,JJ,10th,10th,1,1
3,JJ,11th,11th,1,1
4,JJ,12th,12th,1,1
5,JJ,13th,13th,1,1
6,JJ,14th,14th,1,1
7,JJ,15th,15th,1,1
8,JJ,16th,16th,1,1
9,JJ,17th,17th,1,1
10,JJ,18th,18th,1,1
11,JJ,19th,19th,1,1
12,JJ,1st,1st,1,1
13,JJ,20th,20th,1,1
14,JJ,21th,21th,1,1
15,JJ,22th,22th,1,1
16,JJ,23rd,23rd,1,1
17,JJ,24th,24th,1,1
18,JJ,25th,25th,1,1
19,JJ,26th,26th,1,1
20,JJ,27th,27th,1,1
21,JJ,28th,28th,1,1
22,JJ,29th,29th,1,1
23,JJ,2d,2d,0,1
24,JJ,2nd,2nd,1,1
25,JJ,3-d,3-D,0,1
26,JJ,30th,30th,1,1
27,JJ,3rd,3rd,1,1
28,JJ,4-h,4-H,0,1
29,JJ,40th,40th,1,1
...,...,...,...,...,...
253690,VBZ,yaps,yap,1,0
253691,VBZ,yarns,yarn,1,0
253692,VBZ,yawns,yawn,1,0
253693,VBZ,yawps,yawp,1,0
253694,VBZ,yaws,yaw,1,0
253695,VBZ,yeans,yean,1,0
253696,VBZ,yearns,yearn,1,0
253697,VBZ,yellows,yellow,1,0
253698,VBZ,yells,yell,1,0
253699,VBZ,yelps,yelp,1,0
253700,VBZ,yeses,yes,0,0
253701,VBZ,yesses,yes,0,0
253702,VBZ,yields,yield,1,0
253703,VBZ,yips,yip,0,0
253704,VBZ,yodels,yodel,1,0
253705,VBZ,yokes,yoke,1,0
253706,VBZ,yowls,yowl,1,0
253707,VBZ,yucks,yuck,1,0
253708,VBZ,yuks,yuk,1,0
253709,VBZ,zaps,zap,1,0
253710,VBZ,zeroes,zero,1,0
253711,VBZ,zeros,zero,0,0
253712,VBZ,zigzags,zigzag,1,0
253713,VBZ,zincks,zinc,0,0
253714,VBZ,zincs,zinc,1,0
253715,VBZ,zings,zing,1,0
253716,VBZ,zippers,zipper,0,0
253717,VBZ,zips,zip,1,0
253718,VBZ,zones,zone,1,0
253719,VBZ,zooms,zoom,1,0

In [40]:
plane_exact_word['word'].str[-1:].nunique()

41

In [41]:
plane_exact_word['word'].str[-2:].nunique()

564

In [42]:
plane_exact_word['word'].str[-3:].nunique()

4120

In [43]:
plane_exact_word['word'].str[-4:].nunique()

16799

In [44]:
plane_exact_word['word'].str[-5:].nunique()

39480

Для взятия суффикса у нужного столбца

In [45]:
plane_exact_word['word'].str[-3:]

0         0th
1         0th
2         0th
3         1th
4         2th
5         3th
6         4th
7         5th
8         6th
9         7th
10        8th
11        9th
12        1st
13        0th
14        1th
15        2th
16        3rd
17        4th
18        5th
19        6th
20        7th
21        8th
22        9th
23         2d
24        2nd
25        3-D
26        0th
27        3rd
28        4-H
29        0th
         ...
253690    yap
253691    arn
253692    awn
253693    awp
253694    yaw
253695    ean
253696    arn
253697    low
253698    ell
253699    elp
253700    yes
253701    yes
253702    eld
253703    yip
253704    del
253705    oke
253706    owl
253707    uck
253708    yuk
253709    zap
253710    ero
253711    ero
253712    zag
253713    inc
253714    inc
253715    ing
253716    per
253717    zip
253718    one
253719    oom
Name: word, Length: 253720, dtype: object

In [46]:
plane_exact_word['suff'] = plane_exact_word['word'].str[-3:]#.sample(frac=0.8,random_state=200)

In [47]:
suff_sum = plane_exact_word[['type','suff','PHPMorphy_inflector','SimpleNLG_inflector','en_inflectors_inflector']].groupby(['type', 'suff']).sum()

KeyError: "['SimpleNLG_inflector'] not in index"

In [ ]:
suff_sum

In [ ]:
max_inflector = suff_sum.idxmax(axis=1)

In [ ]:
top_list = suff_sum.apply(lambda s: s.nlargest(suff_sum.shape[1]).index.tolist(), axis=1)

In [ ]:
top_list

In [ ]:
top_list.to_csv('combined_tool_inflector_POS_suffix_rules')

In [ ]:
y = x.drop(['word', 'expected', 'real'], axis=1)
res = y.pivot_table(index='word_operator', columns='type', values='result', aggfunc='mean')
res.T